<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="BankTest"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="95.454">
  <properties />
            <testcase name="customerShouldWithdrawMoneySuccessfully" time="24.401" classname="com.bank.testsuit.BankTest">
                <failure type="java.lang.AssertionError"
                  message="expected [Deposit Successful] but found [Transaction successful]"
              >
<![CDATA[java.lang.AssertionError: expected [Deposit Successful] but found [Transaction successful]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.bank.testsuit.BankTest.customerShouldWithdrawMoneySuccessfully(BankTest.java:154)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="bankManagerShouldOpenAccountSuccessfully" time="16.028" classname="com.bank.testsuit.BankTest" />
                <testcase name="customerShouldDepositMoneySuccessfully" time="25.121" classname="com.bank.testsuit.BankTest" />
                <testcase name="customerShouldLoginAndLogoutSuccessfully" time="20.597" classname="com.bank.testsuit.BankTest" />
                <testcase name="bankManagerShouldAddCustomerSuccessfully" time="9.307" classname="com.bank.testsuit.BankTest" />
      
</testsuite>
